### ISSUE TITLE
RV2 Demo?

### ISSUE THREAD

**Issue by wanted2** [cybercore-co-ltd/CoLAD#2]
I am going to replicate the results and integrate into some fancy demo in my dayoffs.

Can you provide some insights on performance such as the harware specs?

**Comment by chuong98** [comment]
Hello, we train our model on a Server with 4 GPU Quadro RTX 8000 using fp16.
+ Except for very large models, such as X101 Deformable or Swin Transformer, we only use 2GPU, each with 8 images, for most of the experiments.
+ For inference speeds, we will update in the paper later. 
+ Here, we test it on 1 GPU 1080 Ti. To avoid the impact of CPU, we report the fps for the network's inference only (not including pre-processing or post-processing).

<img src="https://user-images.githubusercontent.com/15174756/131556839-8973046e-8977-49a5-b875-c36d927e35fc.png" height="97">

<img src="https://user-images.githubusercontent.com/15174756/131556948-5b1ec245-3e8d-4e3d-bd2e-41414615604f.png" height="100">

Where IO (Implicit Objectness) and COP(Conditional Objectness) are the optional auxiliary prediction added to the PAA head. We found that they are more effective than Centerness or IoU prediction, while only slightly change the computation/inference speed. Please refer to Appendix A for more details.
