### ISSUE TITLE
RV3 Lack of number of parameters

### ISSUE THREAD

**Issue by wanted2** [cybercore-co-ltd/CoLAD#3]
Hi,

Can you add the number of parameters to tables?
Especially, for the student model. Because this number together with inference speed and accuracy, will help readers to choose the model for deployment.

**Comment by chuong98** [comment]
well, like i said, the model number parameters does not change. You can use the tools from mmdetection to get the model complexity: https://mmdetection.readthedocs.io/en/latest/useful_tools.html#model-complexity

**Comment by chuong98** [comment]
defaul
