### ISSUE TITLE
NotImplementedError in colab.py

### ISSUE THREAD

**Issue by haotianll** [cybercore-co-ltd/CoLAD#8]
Hi, thank you for releasing the code!

It seems that the code for the training of CoLAD is not implemented yet, could you please update it?
https://github.com/cybercore-co-ltd/CoLAD/blob/cb888371db60e4973f91bba4f5a79bde0deed2e4/ccdet/models/detectors/colad.py#L58-L64

**Comment by chuong98** [comment]
Thank you, we will add it.

**Comment by chuong98** [comment]
The code was upload. Please retry, thank you.

**Comment by haotianll** [comment]
Thank you so much!
